### ISSUE TITLE
Class 'Rap2hpoutre\FastExcel\FastExcel' not found

### ISSUE THREAD

**Issue by devendrakavya** [rap2hpoutre/fast-excel#120] opened 2019-09-13 07:41 UTC
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Rap2hpoutre\FastExcel\FastExcel;
use App\User;

class TestController extends Controller
{
    public function test()
    {
        // Load users
        $users = User::all();

        // Export all users
        (new FastExcel($users))->export('file.xlsx');
    }
}

**Comment by rap2hpoutre** [comment] 2019-09-30 05:15
duplicate of #121

**Closed by rap2hpoutre** 2019-09-30 05:15 UTC
